apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: perf-pvc-volume
  namespace: multicluster-controlplane
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp3-csi
