#!/usr/bin/env bash

# step1: get AWS IoT broker endpoint (note: different aws acccount)
host=$(aws iot describe-endpoint --endpoint-type iot:Data-ATS | jq -r '.endpointAddress')
port=8883

# step2: download AWS IoT broker severing CA (TODO)

# step3: prepare clients certs for AWS IoT client
# X.509 certificates generated by AWS IoT, or
# X.509 certificates signed by a CA registered with AWS IoT, or
# X.509 certificates signed by a CA that is not registered with AWS IoT (Server Name Indication SNI)

# step4: attach policies for AWS IoT client


# renew

# register AWS IoT thing
# aws iot create-thing --thing-name "PubSubTestThing"
# {
#     "thingName": "PubSubTestThing",
#     "thingArn": "",
#     "thingId": ""
# }
#
# aws iot attach-thing-principal \
#     --thing-name "PubSubTestThing" \
#     --principal ""
