apiVersion: flightctl.io/v1alpha1
kind: Device
metadata:
  name: <name>
spec:
  applications:
  - name: my-app
    appType: compose
    inline:
      - content: |
            version: "3.8"
            services:
              service1:
                image:  quay.io/flightctl-tests/alpine:v1
                command: ["sleep", "infinity"]
        path: podman-compose.yaml
