apiVersion: rbac.open-cluster-management.io/v1alpha1
kind: ClusterPermission
metadata:
  name: kubevirt-edit
spec:
  roleBindings:
  - namespace: kubevirt-workspace-1
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: kubevirt.io:edit
    subject:
      kind: User
      name: user0
      apiGroup: rbac.authorization.k8s.io
  - namespace: kubevirt-workspace-2
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: kubevirt.io:edit
    subject:
      kind: User
      name: user0
      apiGroup: rbac.authorization.k8s.io
