apiVersion: federation-ai.open-cluster-management.io/v1alpha1
kind: Federation
metadata:
  name: my-federation
  namespace: my-federation-workspace
spec:
  framework: "flower" # flower | openfl
  server: # server
    image: "server:1.3"
    imagePullPolicy: "IfNotPresent"
    replicas: 1
    rounds: 5
    listener:
    - name: server
      port: 1234
      tls: false
      type: route # route | ingress | loadbalancer | nodeport | cluster-ip
      serverCA: # Optional
        name: "server-ca" # The name of the Secret containing the server CA.
      authentication: # Optional
          type: mtls
          signingCA:
            name: "singing-ca" # The name of the Secret containing the signing CA, the type must be kubernetes.io/tls.
    config:
      name: "server-config"  # a config for this aggregator, rounds
    placement: # Optional, by default, the server will be deployed in the same namespace as the current CR
      name: "my-federation-server"
  clients: # clients
    image: "client:1.3"
    imagePullPolicy: "IfNotPresent"
    replicas: 3
    dataset:
      source: # this will be mapped to volumes
        persistentVolumeClaim:
          claimName: local-training-data
      dataPath: "/mnt/data" # this will be mapped to mountPath
    placement:
      name: "my-federation-clients"
status:
  conditions:
    - lastTransitionTime: "2024-08-20T10:03:25.444541142Z"
      status: "True"
      type: ServerReady
    - lastTransitionTime: "2024-08-20T10:03:25.444541142Z"
      status: "True"
      type: ClientsReady
