apiVersion: work.open-cluster-management.io/v1
kind: ManifestWork
metadata:
  name: test-namespace
spec:
  workload:
    manifests:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: test1
