apiVersion: v1
kind: Namespace
metadata:
  name: app

---

apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: app
spec:
  selector:
    app: httpbin
  ports:
  - port: 80
    targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
      - name: httpbin
        image: kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
