apiVersion: v1
kind: Service
metadata:
  name: cluster-manager-grpc-lb
  namespace: open-cluster-management-hub
  annotations:
    # Specify the load balancer scheme as internet-facing to create a public-facing Network Load Balancer (NLB)
    # service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  ports:
  - name: grpc
    port: 443
    targetPort: 8090
    protocol: TCP
  selector:
    app: cluster-manager-grpc-server