kind: Deployment
apiVersion: apps/v1
metadata:
  name: klusterlet-work-agent
  labels:
    app: klusterlet-work-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: klusterlet-work-agent
  template:
    metadata:
      labels:
        app: klusterlet-work-agent
    spec:
      serviceAccountName: spoke-sa
      containers:
      - name: work-agent
        image: quay.io/open-cluster-management/work:latest
        imagePullPolicy: IfNotPresent
        args:
          - "/work"
          - "agent"
          - "--spoke-cluster-name=cluster1"
          - "--cloudevents-client-id=cluster1-work-agent"
          - "--workload-source-driver=grpc"
          - "--workload-source-config=/spoke/hub-kubeconfig/config.yaml"
          - "--disable-leader-election"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          runAsNonRoot: true
        volumeMounts:
        - name: hub-kubeconfig-secret
          mountPath: "/spoke/hub-kubeconfig"
          readOnly: true
        - name: bootstrap-secret
          mountPath: "/spoke/bootstrap"
          readOnly: true
      volumes:
      - name: hub-kubeconfig-secret
        secret:
          secretName: hub-kubeconfig-secret
      - name: bootstrap-secret
        secret:
          secretName: bootstrap-secret
