kind: Deployment
apiVersion: apps/v1
metadata:
  name: cluster-manager-registration-controller
  labels:
    app: clustermanager-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clustermanager-registration-controller
  template:
    metadata:
      labels:
        app: clustermanager-registration-controller
    spec:
      serviceAccountName: hub-sa
      containers:
      - name: registration-controller
        image: quay.io/open-cluster-management/registration:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          runAsNonRoot: true
        volumeMounts:
          - name: grpc-server-certs
            mountPath: "/hub/grpc/certs"
            readOnly: true
        args:
          - "/registration"
          - "controller"
          - "--enabled-registration-drivers=grpc"
          - "--grpc-ca-file=/hub/grpc/certs/ca.crt"
          - "--grpc-key-file=/hub/grpc/certs/ca.key"
          - "--disable-leader-election"
      volumes:
      - name: grpc-server-certs
        secret:
          secretName: grpc-server-certs
