kind: Deployment
apiVersion: apps/v1
metadata:
  name: cluster-manager-addon-manager-controller
  labels:
    app: clustermanager-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clustermanager-addon-manager-controller
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: clustermanager-addon-manager-controller
    spec:
      serviceAccountName: hub-sa
      containers:
      - name: addon-manager-controller
        image: quay.io/open-cluster-management/addon-manager:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          runAsNonRoot: true
        args:
          - "/addon"
          - "manager"
          - "--disable-leader-election"
