kind: Deployment
apiVersion: apps/v1
metadata:
  name: cluster-manager-grpc-server
  labels:
    app: clustermanager-grpc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clustermanager-grpc-server
  template:
    metadata:
      labels:
        app: clustermanager-grpc-server
    spec:
      serviceAccountName: hub-sa
      containers:
      - name: grpc-server
        image: quay.io/open-cluster-management/registration:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          runAsNonRoot: true
        volumeMounts:
          - name: grpc-server-config
            mountPath: "/hub/grpc/config"
            readOnly: true
          - name: grpc-server-certs
            mountPath: "/hub/grpc/certs"
            readOnly: true
        ports:
          - containerPort: 8090
        args:
          - "/server"
          - "grpc"
          - "--server-config=/hub/grpc/config/config.yaml"
      volumes:
      - name: grpc-server-config
        configMap:
          name: grpc-server-config
      - name: grpc-server-certs
        secret:
          secretName: grpc-server-certs
