apiVersion: v1
kind: Service
metadata:
  name: cluster-manager-grpc-service
  labels:
    app: clustermanager-grpc-server
spec:
  selector:
    app: clustermanager-grpc-server
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: ClusterIP
