apiVersion: v1
kind: Service
metadata:
  name: cluster-manager-grpc-server-lb
  namespace: open-cluster-management-hub
spec:
  type: LoadBalancer
  ports:
  - name: grpc
    port: 443
    targetPort: 8090
    protocol: TCP
  selector:
    app: cluster-manager-grpc-server
